CREATE TABLE gallery (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  updated DATETIME on update CURRENT_TIMESTAMP() NOT NULL DEFAULT CURRENT_TIMESTAMP,
  posted DATETIME DEFAULT CURRENT_TIMESTAMP,
  display BOOLEAN NOT NULL,
  display_order SMALLINT NOT NULL,
  year TINYTEXT NOT NULL,
  title TINYTEXT NOT NULL,
  medium TINYTEXT NOT NULL,
  dimensions TINYTEXT NOT NULL,
  statement MEDIUMTEXT NOT NULL,
  primary_img TINYTEXT NOT NULL,
  detail_imgs TEXT NOT NULL
);